#ifndef PIT_H
#define PIT_H

#include "Type.h"

#define PIT_FREQUENCY 1193180
#define MSTOCOUNT(X) (PIT_FREQUENCY*X/1000)
#define USTOCOUNT(X) (PIT_FREQUENCY*X/1000000)

#define PIT_PORT_CONTROL 0x43
#define PIT_PORT_COUNTER0 0x40

#define PIT_CONTROL_COUNTER0 0x00
#define PIT_CONTROL_LSBMSBRW 0x30
#define PIT_CONTROL_LATCH 0x00
#define PIT_CONTROL_MODE0 0x00
#define PIT_CONTROL_MODE2 0x04
#define PIT_CONTORL_BCD 0x01
#define PIT_CONTROL_BINARY 0x00

#define PIT_COUNTER0_ONCE (PIT_CONTROL_COUNTER0|PIT_CONTROL_LSBMSBRW|PIT_CONTROL_MODE0|PIT_CONTROL_BINARY)
#define PIT_COUNTER0_PERIODIC (PIT_CONTROL_COUNTER0|PIT_CONTROL_LSBMSBRW|PIT_CONTROL_MODE2|PIT_CONTROL_BINARY)

void kInitializePIT(WORD wCount, BOOL bPeriodic);
WORD kReadPITCounter0();
void kWaitUsingDirectPIT(WORD wCount);

#endif